import Head from "next/head";

export const Header = () => {
  return (
    <Head>
      <title>Fteam</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <script src="https://kit.fontawesome.com/afb4a8eb1c.js" crossorigin="anonymous"></script>
    </Head>
  );
};
