import Head from "next/head";

export const Header = () => {
  return (
    <Head>
      <title>Design House</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="theme-color" content="#ffffff"></meta>
      <meta name="viewport" content="initial-scale=1, width=device-width" />
      <link rel="shortcut icon" href="favicon.png" type="image/x-icon" />
    </Head>
  );
};
